#!/usr/bin/python3 -u
# Upload the container to a registry.  Note this
# is distinct from `upload-oscontainer` which
# only applies to (hopefully soon only older)
# versions of RHCOS but not FCOS.

import argparse
import json
import os
import subprocess
import sys

cosa_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, cosa_dir)

from cosalib import cmdlib

transports = {
    'containers-storage':'containers-storage:',
    'dir':'dir:',
    'docker':'docker://',
    'docker-archive':'docker-archive:',
    'docker-daemon':'docker-daemon',
}

parser = argparse.ArgumentParser()
parser.add_argument("--authfile", help="Authentication file",
                    action='store')
parser.add_argument("--insecure", help="Ignoring SSL/TLS verification, allow insecure registry",
                    action='store_true')
parser.add_argument("--transport", help="destination image transport, support: \
                    containers-storage, dir, docker, docker-archive, docker-daemon",
                    default='docker')
parser.add_argument("name", help="destination image reference")

args = parser.parse_args()

with open('builds/builds.json') as f:
    builds = json.load(f)['builds']
if len(builds) == 0:
    cmdlib.fatal("No builds found")
latest_build = builds[0]['id']
arch = cmdlib.get_basearch()
latest_build_path = f"builds/{latest_build}/{arch}"

metapath = f"{latest_build_path}/meta.json"
with open(metapath) as f:
    meta = json.load(f)
ociarchive = os.path.join(latest_build_path, meta['images']['ostree']['path'])

skopeoargs = ['skopeo', 'copy']
if args.authfile is None:
    args.authfile = os.environ.get("REGISTRY_AUTH_FILE")
if args.authfile is not None:
    skopeoargs.extend(['--authfile', args.authfile])
container_name = args.name
if ":" not in container_name:
    container_name = f"{container_name}:{latest_build}-{arch}"

if args.insecure:
    skopeoargs.extend(["--insecure-policy"])
    skopeoargs.extend(["--dest-tls-verify=false"])

if args.transport not in transports.keys():
    print(f"Not supported transport:{args.transport}")
    exit(1)

skopeoargs.extend([f"oci-archive:{ociarchive}", f"{transports[args.transport]}{container_name}"])
print(subprocess.list2cmdline(skopeoargs))
os.execvp('skopeo', skopeoargs)
